name: CI Full

on:
  push:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  phpcs:
    name: PHP CodeSniffer

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
        tools: cs2pr

    - name: Install Composer dependencies
      uses: ramsey/composer-install@v2

    - name: Run PHPCS on all files
      run: |
        vendor/bin/phpcs -q -n --ignore=vendor --runtime-set installed_paths vendor/wp-coding-standards/wpcs --standard=WordPress-Core --report=checkstyle $GITHUB_WORKSPACE | cs2pr
